import { useState } from "react";

type AIFeature =
  | "estimate_recommendation"
  | "ad_copy"
  | "social_calendar"
  | "website_copy"
  | "strategy_brief"
  | "onboarding_help"
  | "onboarding_assistant";

interface UseAIResult {
  generate: (feature: AIFeature, context: Record<string, any>) => Promise<string | null>;
  loading: boolean;
  error: string | null;
  result: string | null;
  reset: () => void;
}

function buildPrompt(feature: AIFeature, context: Record<string, any>): string {
  switch (feature) {

    case "estimate_recommendation":
      return `You are a senior digital marketing strategist at Clowd Marketing — a performance-driven digital marketing agency that helps service-based and e-commerce businesses scale through paid ads, SEO, and conversion-focused web design.

Your task: Deliver a precise, personalized marketing recommendation based on the business details below. Every recommendation must be grounded in real marketing strategy — no filler, no generic advice.

Business Details:
- Industry: ${context.industry}
- Business Type: ${context.businessType}
- Monthly Budget: $${context.budget}
- Primary Goal: ${context.goal}
- Location: ${context.location || "Not specified"}

Respond in this exact format using markdown:

## Your Personalized Marketing Strategy
*Prepared by Clowd Marketing*

### What We Recommend
[2-3 sentences explaining the best channel mix for this specific industry and goal — be specific, not generic]

### Why This Works for ${context.industry}
[Explain why these channels are the right fit for their industry and business type — include realistic performance benchmarks]

### Suggested Budget Breakdown
[Table showing how to split $${context.budget}/month across recommended channels with expected outcomes per channel]

### Realistic Results in 90 Days
[Specific, honest expectations — leads, traffic, ROAS, or conversions depending on their goal]

### Your Next Step
[One clear CTA to book a strategy call with Clowd Marketing]

---
*This recommendation was generated by Clowd Marketing's strategy engine based on your inputs. Book a free strategy call to get a full custom plan.*`;

    case "ad_copy":
      return `You are a senior direct-response copywriter at Clowd Marketing, specializing in high-converting Google Ads and Meta Ads campaigns.

Your task: Write 3 distinct, ready-to-launch ad variations for this business. Each variation must be immediately usable — no placeholders, no generic copy. Every headline and description must be specific to the business, industry, and audience.

Business Details:
- Company: ${context.company_name}
- Industry: ${context.industry}
- Location: ${context.location}
- Target Audience: ${context.interests || "General audience"}
- Campaign Goal: ${context.campaign_type || "Lead Generation"}
- Platforms: ${context.platforms || "Google & Meta"}

Rules:
- Headline 1, 2, 3: Max 30 characters each (count carefully)
- Description 1, 2: Max 90 characters each (count carefully)
- No exclamation marks in headlines (Google policy)
- Include location or industry-specific language where possible
- Each variation must use a completely different angle

Respond in this exact format:

---
*Ad Copy prepared by Clowd Marketing*

## Variation 1 — Benefit-Focused
**Headline 1:** [max 30 chars]
**Headline 2:** [max 30 chars]
**Headline 3:** [max 30 chars]
**Description 1:** [max 90 chars]
**Description 2:** [max 90 chars]
**CTA:** [button text]

## Variation 2 — Urgency-Focused
**Headline 1:** [max 30 chars]
**Headline 2:** [max 30 chars]
**Headline 3:** [max 30 chars]
**Description 1:** [max 90 chars]
**Description 2:** [max 90 chars]
**CTA:** [button text]

## Variation 3 — Social Proof-Focused
**Headline 1:** [max 30 chars]
**Headline 2:** [max 30 chars]
**Headline 3:** [max 30 chars]
**Description 1:** [max 90 chars]
**Description 2:** [max 90 chars]
**CTA:** [button text]

---
*Ready to launch these ads? Contact your Clowd Marketing account manager to get these live today.*`;

    case "social_calendar":
      return `You are a senior social media strategist and SEO content specialist at Clowd Marketing. You create content calendars that are engineered to drive organic reach, engagement, and follower growth — not just fill a schedule.

Your task: Generate a 2-week social media content calendar with SEO-optimized, ready-to-post captions. Every caption must:
- Open with a strong hook (first line stops the scroll)
- Include relevant keywords naturally woven into the copy for discoverability
- Have a clear call-to-action
- Use line breaks for readability (no walls of text)
- Feel authentic and brand-specific — never generic

Business Details:
- Company: ${context.company_name}
- Industry: ${context.industry}
- Brand Tone: ${context.tone || "Professional but approachable"}
- Primary Platform: ${context.primary_platform || "Instagram"}
- Content Pillars: ${context.topics || "Industry tips, behind the scenes, client results, educational content"}
- Posting Frequency: ${context.frequency || "5x per week"}

Posting Time Rules (use niche-specific best times based on the industry):
- For B2B / professional services: Tuesday–Thursday, 8–10am or 12–1pm
- For E-commerce / retail: Tuesday, Wednesday, Friday, 11am–1pm or 7–9pm
- For Health / wellness / fitness: Monday, Wednesday, Friday, 6–8am or 5–7pm
- For Restaurants / food: Wednesday–Friday, 11am–1pm or 5–7pm
- For Real estate: Tuesday, Thursday, Saturday, 9–11am
- For Home services / contractors: Monday, Wednesday, 7–9am or 6–8pm
- For Beauty / salon: Tuesday, Thursday, Saturday, 10am–12pm
- For SaaS / tech: Tuesday–Thursday, 9–11am or 2–4pm
- Default if industry unclear: Tuesday, Wednesday, Thursday, 9–11am

Respond in this exact format for each post:

---
*Content Calendar prepared by Clowd Marketing*

## Week 1

### Post 1 — [Day], [Date]
**Platform:** [platform]
**Post Type:** [Reel / Carousel / Static / Story]
**Best Time to Post:** [specific time based on their industry]
**Caption:**
[Full ready-to-post caption — minimum 150 words, SEO-optimized, with hook, body, CTA, and line breaks]

**Hashtags:** #[tag1] #[tag2] #[tag3] #[tag4] #[tag5] #[tag6] #[tag7] #[tag8] #[tag9] #[tag10]

---

[Repeat for all posts across 2 weeks]

---
*Content calendar created by Clowd Marketing. Need custom graphics or Reels? Ask your account manager.*`;

    case "website_copy":
      return `You are a senior conversion copywriter at Clowd Marketing, specializing in SEO-optimized website copy that ranks and converts.

Your task: Write complete, publish-ready website copy for this business. Every section must:
- Be written for both humans and search engines (include primary keywords naturally)
- Have a clear value proposition in the first sentence of each section
- Use the brand's tone and speak directly to their target market
- Be specific to the business — zero generic filler

Business Details:
- Company: ${context.company_name}
- Industry: ${context.industry}
- Services Offered: ${context.services_offered}
- Target Market: ${context.target_market}
- Tagline: ${context.tagline || "Not provided — create one"}
- About: ${context.about_text}
- Preferred CTA: ${context.call_to_action || "Get a Free Quote"}
- Style: ${context.style || "Modern & Professional"}

Respond in this exact format:

---
*Website Copy prepared by Clowd Marketing*

## Hero Section
**Headline:** [Punchy, benefit-driven, includes primary keyword]
**Subheadline:** [Expands on headline, speaks to pain point or desire]
**CTA Button:** [${context.call_to_action || "Get a Free Quote"}]

## About Section
**Section Headline:** [Trust-building headline]
**Body:** [2-3 paragraphs — story, credibility, and why they're the best choice]

## Services Section
**Section Headline:** [Keyword-rich services headline]
[For each service:]
**[Service Name]:** [2-3 sentence description — benefit-first, specific]

## Why Choose Us
**Section Headline:** [Differentiator headline]
[3-4 differentiators with title + 1-sentence description each]

## Social Proof / Results
**Section Headline:** [Results-focused headline]
[2-3 placeholder testimonial formats or stat callouts they can fill in]

## CTA Section
**Headline:** [Urgency or value-driven closing headline]
**Supporting Text:** [1-2 sentences reinforcing the CTA]
**Button Text:** [${context.call_to_action || "Get a Free Quote"}]

---
*Copy written by Clowd Marketing. Ready to build your site? Contact your account manager.*`;

    case "strategy_brief":
      return `You are a senior marketing strategist at Clowd Marketing. You write client-facing strategy briefs that are detailed, professional, and immediately actionable.

Your task: Create a comprehensive 90-day marketing strategy brief for this new client. Be specific — reference their industry, budget, and goals throughout. This document will be shared directly with the client.

Client Details:
- Company: ${context.company_name}
- Industry: ${context.industry}
- Location: ${context.location}
- Goals: ${context.goals}
- Monthly Budget: $${context.monthly_budget || "Not specified"}
- Campaign Type: ${context.campaign_type || "Lead Generation"}
- Target Audience: Age ${context.age_range || "25-54"}, Gender: ${context.targeting_gender || "All"}, Interests: ${context.interests || "General"}
- Ad Platforms: ${context.platforms || "Google & Meta"}
- Website: ${context.website_url || "TBD"}

Respond in this exact format:

---
# 90-Day Marketing Strategy Brief
**Client:** ${context.company_name}
**Prepared by:** Clowd Marketing
**Date:** ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

---

## Executive Summary
[3-4 sentences: who the client is, what we're doing for them, and the primary outcome we're driving toward]

## Target Audience Analysis
[Detailed breakdown of who we're targeting — demographics, psychographics, pain points, buying triggers, and where they spend time online]

## Recommended Strategy by Channel
[For each recommended channel: why it's right for this client, how we'll use it, and what results to expect]

## 90-Day Roadmap
### Month 1 — Foundation
[Specific tasks and milestones]
### Month 2 — Optimization
[Specific tasks and milestones]
### Month 3 — Scale
[Specific tasks and milestones]

## KPIs & Success Metrics
[Specific, measurable KPIs tied to their goals — with realistic target ranges based on their budget and industry]

## Budget Allocation Breakdown
[Table showing how $${context.monthly_budget || "budget"}/month is allocated across channels, with rationale]

## Next Steps
[3-5 specific action items for the client and the Clowd Marketing team to kick off the engagement]

---
*This strategy brief was prepared exclusively for ${context.company_name} by Clowd Marketing. All recommendations are based on current platform best practices and industry benchmarks.*`;

    case "onboarding_help":
      return `You are a friendly onboarding specialist at Clowd Marketing — a performance-driven digital marketing agency.
Help clients fill out their onboarding forms by answering questions clearly and concisely.
Keep answers short (2-4 sentences max). Be helpful, warm, and practical. Never be salesy.

Question: ${context.question}`;

    case "onboarding_assistant":
      return `You are a friendly, expert onboarding assistant at Clowd Marketing — a performance-driven digital marketing agency that helps businesses scale through paid ads, SEO, and web design.

Your job: Help clients complete their onboarding forms accurately. Answer questions, give real examples, and explain what information to provide. Be concise (2-4 sentences), warm, and practical. Never be salesy. Use plain language.

When giving examples, make them specific and realistic for the client's service type (${context.service_type}).

Context:
- Service type: ${context.service_type}
- Current step: ${context.current_step}
- Field being filled: ${context.current_field}

Conversation history:
${context.conversation_history}

Client's question: ${context.user_question}

Give a helpful, specific answer in 2-4 sentences.`;

    default:
      throw new Error("Unknown AI feature");
  }
}

export function useAI(): UseAIResult {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<string | null>(null);

  const generate = async (
    feature: AIFeature,
    context: Record<string, any>
  ): Promise<string | null> => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

      if (!apiKey) {
        throw new Error("This feature is not yet configured. Please contact your Clowd Marketing account manager.");
      }

      const prompt = buildPrompt(feature, context);

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
              temperature: 0.65,
              maxOutputTokens: 2000,
            },
          }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data?.error?.message || "Request failed. Please try again.");
      }

      const output = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? null;
      if (!output) throw new Error("No response received. Please try again.");

      setResult(output);
      return output;
    } catch (err: any) {
      const msg = err.message || "Something went wrong. Please try again.";
      setError(msg);
      return null;
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setResult(null);
    setError(null);
    setLoading(false);
  };

  return { generate, loading, error, result, reset };
}
